# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  schedule:
    - cron: "0 3 * * *"  # UTC時間で毎日3時に実行
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Get latest cedec session list
        run: curl -O "https://stat.cedec.cesa.or.jp/assets/json/2025/cedec_schedule.json"
      - name: Create github issues for CEDEC sessions
        uses: actions/github-script@v7
        with:
          script: |
            const issues_response = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            const issues = issues_response.data;
            const issue_titles = issues.map((issue_json) => {
              return issue_json.title;
            });
            for (const issue_title of issue_titles) {
              console.log(issue_title);
            }
            const cedec_schedule_url = "https://stat.cedec.cesa.or.jp/assets/json/2025/cedec_schedule.json";
            const cedec_schedule_response = await fetch(cedec_schedule_url);
            const sessions = await cedec_schedule_response.json();
            var flag = false;
            for (const session of sessions) {
              if (issue_titles.includes(session.title)) {
                console.log(`セッション${session.title}のissueは既にあるのでスキップ.`);
              } else {
                if (flag) {
                  console.log(`セッション${session.title}のissueは無いですが、大量作成防止フラグが立ってるのでスキップ。`);
                } else {
                  console.log(`セッション${session.title}のissueを作成します。`);
                  await github.rest.issues.create({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    title: "テスト",
                    body: "テスト",
                    labels: ["automation"]
                  });
                  flag = true;
                }
              }
            }
