# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  schedule:
    - cron: "0 3 * * *"  # UTC時間で毎日3時に実行
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Create github issues for CEDEC sessions
        uses: actions/github-script@v7
        with:
          script: |
            const issues_response = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            const issues = issues_response.data;
            const issue_titles = issues.map((issue_json) => {
              return issue_json.title;
            });
            const cedec_schedule_url = "https://stat.cedec.cesa.or.jp/assets/json/2025/cedec_schedule.json";
            const cedec_schedule_response = await fetch(cedec_schedule_url);
            const sessions = await cedec_schedule_response.json();
            for (const session of sessions) {
              if (issue_titles.includes(session.title)) {
                console.log(`セッション${session.title}のissueは既にあるのでスキップ.`);
              } else {
                console.log(`セッション${session.title}のissueを作成します。`);
                var date_desc;
                var date_label_simple;
                var date_label_detail;
                if (session.start == "") {
                  date_desc = "-";
                  date_label_simple = null;
                  date_label_detail = null;
                } else {
                  date_desc = `${session.start} ～ ${session.end.split(" ")[1]}`;
                  date_label_detail = session.start.split(" ")[0];
                  switch (session.start.split(" ")[0]) {
                  case "2025/07/22":
                    date_label_simple = "1日目";
                    break;
                  case "2025/07/23":
                    date_label_simple = "2日目";
                    break;
                  case "2025/07/24":
                    date_label_simple = "3日目";
                    break;
                  default:
                    console.log(`unexpected schedule. start=${session.start} end=${session.end}`);
                  }
                }
                await github.rest.issues.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: `${session.title}`,
                  body: `## セッション情報
            | 項目 | 値 |
            |:------|:------|
            | 日時 | ${date_desc} |
            | 形式 | ${session.format} |
            | 登壇者 | ${session.speakers.map((speaker) => `${speaker.company}　${speaker.name}　様`).join(", ")} |
            | カテゴリー | ${session.category} |
            | サブカテゴリー | ${session.sub_category.join(", ")} |
            | 難易度 | ${session.difficulty} |
            | 写真撮影 | ${session.photo_ok ? "可" : "不可" } |
            | SNS投稿 | ${session.sns_ok ? "可" : "不可"}
            | CEDIL公開予定 | ${session.CEDIL ? "あり" : "なし"} |
            | URL | ${session.URL} |
            
            ## 参加ガイドライン
            - このセッションに参加するにはリアクションしてください
              - 現地で参加したい人は、:rocket:でリアクションしてください
              - 家で参加したい人は、:eyes:でリアクションしてください
              - 誰かに見て欲しい場合は、:heart:でリアクションしてください`,
                labels: [ "automation", date_label_simple, date_label_detail, session.format, session.category, session.photo_ok ? "写真撮影可" : "写真撮影不可", session.sns_ok ? "SNS投稿可" : "SNS投稿不可", session.CEDIL ? "CEDIL公開予定あり" : "CEDIL公開予定なし" ].filter(v => v != null)
                });
              }
            }
